### ISSUE TITLE
Collaborate with crate-ci?

### ISSUE THREAD

**Issue by epage** [crate-ci/azure-pipelines#2]
crate-ci is trying to be a central place for [documentation](https://crate-ci.github.io/) and supporting [tools](https://github.com/crate-ci) to help people have the latest greatest CI.  It was born out of frustration with everyone blogging about their own approach and trying to figure out how to synthesize it all.

We have some basic templates and have started on an equivelant of trust's tool to download binaries from github releases

See https://github.com/crate-ci/resources

**Comment by jonhoo** [comment]
Link to [relevant discussion on Reddit](https://www.reddit.com/r/rust/comments/cc4k9x/rustypipes_easy_continuous_integration_for_rust/etm8fnz/).

**Comment by jonhoo** [comment]
I wonder how valuable it is to have resources for multiple CIs in the same repository. I could see that getting unwieldy quite quickly. See for example the sheer length of the README for this repo. Are we sure it'd be advantageous to merge all into one? Perhaps we could just move this repo in under the `crate-ci` org, but otherwise leave it as a separate project?

**Comment by epage** [comment]
So my expectation was that the documentation would live in the crate-ci book.  Maybe it makes sense to not have all of it there and to instead introduce people to it in the Book and then have more specialized documentation.

I went with a single resources repo in order since I was also putting the install scripts in it which are CI agnostic.  Maybe it makes sense to move those to their own repo?

**Comment by epage** [comment]
and if you want to discuss in real-time, we can hop over to [gitter](https://gitter.im/crate-ci/general?source=orgpage)
