### ISSUE TITLE
Add example to publish crate documentation using Azure pipeline

### ISSUE THREAD

**Issue by jethrosun** [crate-ci/azure-pipelines#69]
I have tried to use Azure pipeline but it didn't work.

**Comment by epage** [comment]
I'm curious, what is your use case for publishing documentation outside of what docs.rs provides?

**Comment by jethrosun** [comment]
@epage Yeah, my situation is a bit weird. I am working on a research prototype ([NetBricks](https://github.com/NetSys/NetBricks)) that it is no longer maintained. I don't think I should publish the project on doc.rs since I am not the owner of it.

**Comment by epage** [comment]
Interesting.  The sad thing is we are becoming so reliant on docs.rs, as a community, that efforts to help publish documentation on our own have been disappearing.  For example, support for it in `cargo-release` was deprecated and then removed.  Because of that, I'm also a bit unsure of the value of us maintaining documentation for the proces.

**Comment by jethrosun** [comment]
@epage I have found out that the [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) still uses azure pipeline for generating docs. One other use case could be that the developers want to host a separate doc page which enables documentation for private fields etc.

**Comment by jethrosun** [comment]
Closed, other people can take a look at [rust-azure-pipelines](https://github.com/xoac/rust-azure-pipelines)
